name: Deploy Backend

on:
  push:
    branches: [ "deploy" ]
    paths: 
      - "backend/**"
      - ".github/workflows/backend-deploy.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login en Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build y Push de la imagen a ECR
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          ECR_REPOSITORY: tienda-backend
          IMAGE_TAG: latest
        run: |
          cd backend
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Despliegue automático en EC2 vía SSM
        env:
          INSTANCE_ID: ${{ secrets.EC2_BACKEND_INSTANCE_ID }}
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          DB_HOST: ${{ secrets.DB_PRIVATE_IP }}
        run: |
          aws ssm send-command \
            --instance-ids "$INSTANCE_ID" \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
              "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin '"$ECR_REGISTRY"'",
              "docker pull '"$ECR_REGISTRY"'/tienda-backend:latest",
              "docker stop tienda-backend || true",
              "docker rm tienda-backend || true",
              "docker run -d --restart unless-stopped --name tienda-backend -p 3001:3001 -e DB_HOST='"$DB_HOST"' -e DB_USER=root -e DB_PASSWORD=admin123 -e DB_NAME=tienda_perritos -e DB_PORT=3306 '"$ECR_REGISTRY"'/tienda-backend:latest"
            ]'